In [ ]:
import torch
import torch.nn as nn
import numpy as np
import random
import pandas as pd

In [ ]:
!pip install pyreader

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pyreader in /usr/local/lib/python3.8/dist-packages (0.0.1)

In [ ]:
!pip install pyreadr
# import pyreader
try:
    import google.colab
    # Running on Google Colab, so install Biopython first
    !pip install biopython
except ImportError:
    pass
import os
import sys

from urllib.request import urlretrieve

import Bio
from Bio import SeqIO, SearchIO, Entrez
from Bio.Seq import Seq
from Bio.SeqUtils import GC
from Bio.Blast import NCBIWWW
from Bio.Data import CodonTable

print("Python version:", sys.version_info)
print("Biopython version:", Bio.__version__)
import numpy as np

import gzip
from mimetypes import guess_type
from functools import partial

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting pyreadr
  Downloading pyreadr-0.4.7-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (364 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 365.0/365.0 KB 7.4 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.8/dist-packages (from pyreadr) (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.2.0->pyreadr) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.2.0->pyreadr) (1.22.4)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.2.0->pyreadr) (2022.7.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.7.3->pandas>=1.2.0->pyreadr) (1.15.0)
Installing collected packages: pyreadr
Successfully installed pyreadr-0.4.7
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting biopython
  Downloading biopython-1.81-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 31.0 MB/s eta 0:00:00
Requirement already satisfied: numpy in /usr/local/lib/python3.8/dist-packages (from biopython) (1.22.4)
Installing collected packages: biopython
Successfully installed biopython-1.81
Python version: sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
Biopython version: 1.81

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pyreadr

In [ ]:
import pyreader
raw_data_brca_path = "/content/drive/MyDrive/MSC/CH3_Project/Spatial Methyl/raw_data/BRCA.RData"
raw_data_luad_path = "/content/drive/MyDrive/MSC/CH3_Project/Spatial Methyl/raw_data/LUAD.RData"
probe_to_serrounding_seq_path = "/content/drive/MyDrive/MSC/CH3_Project/res/hg_chromosoms/probeToSurroundingSeqFilePrefixAll/probe_to_surroundingSeq.csv"
probe_to_serrounding_seq_one_hot_path= "/content/drive/MyDrive/MSC/CH3_Project/res/probe_to_surrounding_seq_one_hot.csv"

raw_data_brca = pyreadr.read_r(raw_data_brca_path)
raw_data_luad = pyreadr.read_r(raw_data_luad_path)

methyl_brca = raw_data_brca['methyl']
methyl_luad = raw_data_luad['methyl']
expression_brca = raw_data_brca['expressi']
expression_luad = raw_data_luad['expressi']

In [ ]:
expression_brca = raw_data_brca['expressi'].reset_index()
expression_luad =  raw_data_luad['expressi'].reset_index()
expression = pd.concat([expression_brca, expression_luad], axis=1, join="inner")
expression = expression.T
expression.columns=expression.iloc[0]
expression = expression.iloc[1:]
expression.columns.name='Unnamed'
expression.to_csv("/content/drive/MyDrive/MSC/CH3_Project/res/sampled/expression.csv")
expression

Unnamed,ARHGEF10L,HIF3A,RNF17,RNF10,RNF11,RNF13,GTF2IP1,REM1,MTVR2,RTN4RL2,...,STRA13,IGFL2,BTN2A3,BTN2A2,BTN2A1,ELF2,ELF5,ELF4,RPS23,MRPL21
TCGA.3C.AAAU.01,10.4713,2.3606,0.0,11.6317,11.2053,10.1911,12.3502,4.0452,0.7564,7.6254,...,9.4519,4.4383,4.2155,7.1175,9.2105,9.5185,0.7564,9.5776,12.9991,8.4289
TCGA.3C.AALI.01,9.2228,0.6265,0.6265,11.8757,10.4259,10.1674,12.4482,4.1138,2.265,6.742,...,10.9444,6.329,4.731,8.4695,9.2514,9.8833,8.9346,9.2307,12.0287,8.6066
TCGA.3C.AALJ.01,10.9468,0.931,0.0,12.2616,10.7842,9.5713,12.754,4.9504,0.0,5.2197,...,10.0827,4.0367,4.7217,8.5349,9.1303,9.31,0.0,9.0511,13.453,8.9463
TCGA.3C.AALK.01,9.9856,2.6732,0.0,11.9567,11.0071,10.0354,12.6732,5.0382,0.0,5.5899,...,11.0631,6.948,4.8018,7.9201,9.0848,9.6189,5.3909,9.1451,13.4669,8.5651
TCGA.4H.AAAK.01,10.2842,2.272,0.0,11.7566,10.8499,9.9325,12.3191,3.1835,0.8884,6.1192,...,9.5116,6.6703,4.7063,8.2151,9.176,9.8923,4.4496,9.3203,13.4995,8.6733
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA.NJ.A55O.01,9.5666,7.3861,0.0,11.6789,10.4147,10.4301,12.5656,4.0152,0.0,5.2608,...,0.663,0.663,4.8582,0.663,9.7683,12.3221,8.3486,11.4734,6.5865,10.5539
TCGA.NJ.A55R.01,11.4047,8.4763,0.7832,12.2667,10.5853,9.9811,12.1121,4.8755,0.3107,8.2994,...,0.0,1.4233,6.0934,0.0,9.3946,11.4603,7.9709,10.7769,7.247,10.4246
TCGA.NJ.A7XG.01,9.9184,9.1379,0.0,11.7534,10.3786,9.5528,12.4165,2.9762,1.7179,9.3132,...,0.0,0.0,2.3565,0.0,9.2923,11.0366,7.0884,10.5113,4.2718,10.0103
TCGA.O1.A52J.01,9.6611,6.7444,0.0,12.171,10.1368,10.3034,12.0033,3.335,0.9686,8.4602,...,1.2842,0.5641,5.167,3.5855,8.1364,11.3414,6.9704,11.3857,4.6115,9.8352
TCGA.S2.AA1A.01,10.1386,6.1115,1.2081,11.5402,10.6471,10.5838,12.845,7.155,0.0,4.5809,...,0.0,0.0,5.5504,0.0,9.1541,12.3448,7.5117,11.8182,9.0757,10.9878

In [ ]:
class Conf:

    dir_hg19 = "/content/drive/MyDrive/MSC/CH3_Project/res/hg_chromosoms"
    checkpoint_dir = ''
    numSurrounding = 400  # per side of CpG i.e. total is x2
    chrArr = [str(i) for i in range(1,23)]
    chrArr.extend(['X', 'Y'])
    suffix = ''

    ### YOUR SETTINGS - START ###
    filename_sequence = 'probeToOneHotAll.csv'
    filename_expression = 'TCGA_E_final_transposed.csv'
    filename_dist = 'distances.csv'
    filename_labels = 'TCGA_CH3_final.csv'  # lessDecimals.csv'

    validation_portion_subjects = 0.1
    validation_portion_probes = 0.1
    train_portion_probes = 0.7

    ### YOUR SETTINGS - END ###

    # Below conf files are intended for use ONLY in dataProcessor, not in model code
    probeToSurroundingSeqFilePrefixAll = '/content/drive/MyDrive/MSC/CH3_Project/res/hg_chromosoms/probeToSurroundingSeqFilePrefixAll/probe_to_surroundingSeq'
    probeToSurroundingSeqFilePrefixChr = '/content/drive/MyDrive/MSC/CH3_Project/res/hg_chromosoms/probeToSurroundingSeqFilePrefixChr/probe_to_surroundingSeq'

    probeToOneHotMtrxFilePrefixChr = '../res/probeToOneHotMtrx_'

    probeToOneHotMtrxFilePrefixAll = '../res/probeToOneHotMtrxAll'+str(suffix)
    probeToOneHotPrefixAll = '../res/probeToOneHotAll'+str(suffix)
    probeToOneHotPrefixChr = '../res/probeToOneHotChr_'+str(suffix)
    numBases = 5
    dfDistances = '../res/distances.csv'
    dfMethylName = 'combined_CH3'
    dfMethyl_BRCA = '/content/drive/MyDrive/MSC/CH3_Project/res/BRCA_methyl.csv'
    dfMethyl_normal = '/content/drive/MyDrive/MSC/CH3_Project/res/Normal_methyl.csv'
    dfExpression_BRCA = '/content/drive/MyDrive/MSC/CH3_Project/res/BRCA_expression.csv'
    dfExpression_normal = '/content/drive/MyDrive/MSC/CH3_Project/res/Normal_expression.csv'

    numSampleInputCpgs = 4
    numInputCpgs = 5000

    epochs = 2
    batch_size = 32
    num_steps = 50000

In [ ]:
# dfMethyl file is a file contains the start and end location of each of the CpG sites, and it's probe

dfMethyl_path = "/content/drive/MyDrive/MSC/CH3_Project/res/450k_probes_ChroMM.bed"
dfMethyl = pd.read_csv(dfMethyl_path, header=0, sep='\t', dtype={'Chr': object})
for col in dfMethyl.columns:
  print(f"Column {col}, unique values are:")
  print(dfMethyl[col].unique(), "\n")

Column chr, unique values are:
['chr1' 'chr10' 'chr11' 'chr12' 'chr13' 'chr14' 'chr15' 'chr16' 'chr17'
 'chr18' 'chr19' 'chr2' 'chr20' 'chr21' 'chr22' 'chr3' 'chr4' 'chr5'
 'chr6' 'chr7' 'chr8' 'chr9' 'chrX' 'chrY']

Column start, unique values are:
[   15865    18827    29407 ... 28555536 28555550 28555912]

Column end, unique values are:
[   15866    18828    29408 ... 28555537 28555551 28555913]

Column probe, unique values are:
['cg13869341' 'cg14008030' 'cg12045430' ... 'cg21106100' 'cg08265308'
 'cg14273923']

Column chromHMM, unique values are:
['Heterochromatin' 'CTCF' 'Promoter' 'CTCF+Promoter' 'Enhancer'
 'Transcribed' 'CTCF+Enhancer' 'Repressed' 'Poised_Promoter' 'Repeat']

In [ ]:
dfMethyl

         chr     start       end       probe         chromHMM
0       chr1     15865     15866  cg13869341  Heterochromatin
1       chr1     18827     18828  cg14008030  Heterochromatin
2       chr1     29407     29408  cg12045430  Heterochromatin
3       chr1     29425     29426  cg20826792  Heterochromatin
4       chr1     29435     29436  cg00381604  Heterochromatin
...      ...       ...       ...         ...              ...
485507  chrY  27009430  27009431  cg17939569  Heterochromatin
485508  chrY  27210334  27210335  cg13365400  Heterochromatin
485509  chrY  28555536  28555537  cg21106100  Heterochromatin
485510  chrY  28555550  28555551  cg08265308  Heterochromatin
485511  chrY  28555912  28555913  cg14273923  Heterochromatin

[485512 rows x 5 columns]

In [ ]:
def getSurroundingSeqTablePerChr(chr, dfOut, offset=Conf.numSurrounding):
    dfProbeToSeq = []
    dfMethyl["chr"] = dfMethyl["chr"].apply(str)
    dfMethylCurrent = dfMethyl[dfMethyl["chr"]=="chr"+chr]
    chr_seq_file = os.path.join(dir_hg19, "chr"+str(c)+".fa.gz")
    with partial(gzip.open, mode='rt')(chr_seq_file) as f:
      record = [record for record in SeqIO.parse(f, 'fasta')][0]
    for i in range(len(dfMethylCurrent)):
        print(str(i)+" out of %d" %len(dfMethylCurrent))
        probeID = dfMethylCurrent["probe"].iloc[i]
        pos = int(dfMethylCurrent["start"].iloc[i])
        seq = record[pos-offset:pos+offset]
        dfProbeToSeq.append([probeID, str(seq.seq)])
    dfSurroundingSeqInterim = pd.DataFrame(dfProbeToSeq)
    return dfSurroundingSeqInterim, dfProbeToSeq

In [ ]:
dir_hg19 = '/content/drive/MyDrive/MSC/CH3_Project/res/hg_chromosoms'
dfMethyl_path = "/content/drive/MyDrive/MSC/CH3_Project/res/450k_probes_ChroMM.bed"
probe_to_surrounding_exists = True

if probe_to_surrounding_exists==False:
    chrArr = [str(i) for i in range(1,23)]
    chrArr.extend(['X','Y'])
    dfMethyl = pd.read_csv(dfMethyl_path, header=0, sep='\t', dtype={'Chr': object})
    dfSurroundingSeq = []
    # for c in chrArr:
    for c in chrArr: #for experiement, only chrom 1 for now
        dfSurroundingSeqInterim, probeToSeqPerChr = getSurroundingSeqTablePerChr(c, dfSurroundingSeq, Conf.numSurrounding)
        try:
            dfSurroundingSeqInterim.columns = ["probe", "seq"]
        except:
            pass
        dfSurroundingSeqInterim.to_csv(Conf.probeToSurroundingSeqFilePrefixChr+str(c)+'_.csv', index=None)
        dfSurroundingSeq.extend(probeToSeqPerChr)

    dfSurroundingSeq = pd.DataFrame(dfSurroundingSeq)
    dfSurroundingSeq.columns = ["Probe", "Seq"]
    dfSurroundingSeq.to_csv(Conf.probeToSurroundingSeqFilePrefixAll+'_.csv', index=None)
    dfMethyl.to_csv(Conf.probeToSurroundingSeqFilePrefixAll+'_.csv', index=None)

# Data Pre Processing

Raw data processing

In [ ]:
raw_data_brca_path = '/content/drive/MyDrive/MSC/CH3_Project/Spatial Methyl/raw_data/BRCA.RData'
raw_data_luad_path = '/content/drive/MyDrive/MSC/CH3_Project/Spatial Methyl/raw_data/LUAD.RData'

In [ ]:
full_preprocessing  = False

if full_preprocessing:
  import pyreadr
  raw_data_brca = pyreadr.read_r(raw_data_brca_path)
  raw_data_luad = pyreadr.read_r(raw_data_luad_path)

  methyl_brca = raw_data_brca['methyl']
  expression_brca = raw_data_brca['expressi']
  methyl_luad = raw_data_luad['methyl']
  expression_luad = raw_data_luad['expressi']
  print(f"methyl_brca shape is {methyl_brca.shape}")
  print(methyl_brca.head())
  print(f"expression_brca shape is {expression_brca.shape}")
  print(expression_brca.head())
  print(f"methyl_luad shape is {methyl_luad.shape}")
  print(methyl_luad.head())
  print(f"expression_luad shape is {expression_luad.shape}")
  print(expression_luad.head())

In [ ]:
expression_brca

,TCGA.3C.AAAU.01,TCGA.3C.AALI.01,TCGA.3C.AALJ.01,TCGA.3C.AALK.01,TCGA.4H.AAAK.01,TCGA.5L.AAT0.01,TCGA.5L.AAT1.01,TCGA.5T.A9QA.01,TCGA.A1.A0SB.01,TCGA.A1.A0SE.01,...,TCGA.UL.AAZ6.01,TCGA.UU.A93S.01,TCGA.V7.A7HQ.01,TCGA.W8.A86G.01,TCGA.WT.AB41.01,TCGA.WT.AB44.01,TCGA.XX.A899.01,TCGA.XX.A89A.01,TCGA.Z7.A8R5.01,TCGA.Z7.A8R6.01
rownames,,,,,,,,,,,,,,,,,,,,,
ARHGEF10L,10.4713,9.2228,10.9468,9.9856,10.2842,10.3388,9.5616,9.3663,10.8075,9.7179,...,10.3545,9.2888,9.7473,10.3940,9.2068,9.0903,9.9484,10.5355,10.1557,10.3032
HIF3A,2.3606,0.6265,0.9310,2.6732,2.2720,2.7795,3.3169,1.0328,6.0416,3.3983,...,3.6062,1.6648,7.8227,2.2621,3.5899,2.9100,5.3068,5.6061,2.5307,2.0468
RNF17,0.0000,0.6265,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.5366,0.0000,...,0.4846,0.0000,0.0000,0.0000,0.0000,0.0000,1.7494,0.0000,0.0000,0.4308
RNF10,11.6317,11.8757,12.2616,11.9567,11.7566,12.0236,12.0956,12.1706,11.8120,11.3219,...,12.0146,12.1794,11.7884,11.4804,11.8455,12.2658,11.7505,12.1549,12.0280,11.9773
RNF11,11.2053,10.4259,10.7842,11.0071,10.8499,10.5895,10.8394,10.0400,11.3068,11.2617,...,9.8875,10.4230,10.1715,11.2389,9.3179,10.3775,10.8405,10.8106,10.8124,10.4298
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
PTRF,11.4006,12.1666,12.5534,13.0257,13.1156,13.1050,12.4600,9.3732,13.3508,12.6287,...,10.8612,10.2606,13.1576,12.8143,12.3264,13.4568,12.7931,13.4263,13.0560,11.9785
BCL6B,7.8250,8.1093,8.7597,7.9614,7.6902,8.4416,8.4130,6.6417,5.8179,8.0530,...,6.8920,7.2570,7.7211,8.0178,7.6646,7.7659,8.7220,8.7683,8.4080,7.8409
GSTK1,12.1997,10.7031,12.0469,11.3719,10.8298,11.4331,11.2701,10.7065,10.5362,11.0453,...,11.6911,11.4179,12.3415,11.9708,12.6303,12.0070,11.2346,10.7302,12.2397,10.6544
SELP,5.6018,5.5942,5.6941,8.6253,5.7256,8.3692,8.2680,1.0328,4.0283,7.8723,...,2.0683,4.6782,5.7539,7.0546,7.5898,5.5426,9.0351,8.1007,9.1824,5.2436
SELS,9.7282,10.0766,10.1682,10.2333,10.0402,10.2588,10.0877,10.9767,9.4571,9.8006,...,11.2853,11.1876,10.5979,10.1555,10.1635,10.1305,9.9158,10.2417,10.3759,10.0587

Saving fies of the Methyl DF and Expression DF for both braca and luad

In [ ]:
dfMethyl_BRCA = '/content/drive/MyDrive/MSC/CH3_Project/res/BRCA_methyl_with_index.csv'
dfMethyl_normal = '/content/drive/MyDrive/MSC/CH3_Project/res/LUAD_methyl_with_index.csv'
dfExpression_BRCA = '/content/drive/MyDrive/MSC/CH3_Project/res/BRCA_expression_with_index.csv'
dfExpression_normal = '/content/drive/MyDrive/MSC/CH3_Project/res/LUAD_expression_with_index.csv'
import os.path
from os import path
if full_preprocessing:
  expression_brca.to_csv(dfExpression_BRCA)
  expression_luad.to_csv(dfExpression_normal)
  methyl_brca.to_csv(dfMethyl_BRCA)
  methyl_luad.to_csv(dfMethyl_normal)

In [ ]:
probe_to_serrounding_seq_path= "/content/drive/MyDrive/MSC/CH3_Project/res/hg_chromosoms/probeToSurroundingSeqFilePrefixAll/probe_to_surroundingSeq__.csv"
probe_to_serrounding_seq = pd.read_csv(probe_to_serrounding_seq_path)

In [ ]:
probe_to_serrounding_seq["Seq"] = probe_to_serrounding_seq["Seq"].str.upper()
probe_to_serrounding_seq.shape
probe_to_serrounding_seq

             Probe                                                Seq
0       cg13869341  TCTAAAAATATCTCAGGAGGCTGCAGTGGCTGACCATTGCCTTGGA...
1       cg14008030  CACCTCCTGCTTCTAACAGCAGAGCTGCCAGGCCAGGCCCTCAGGC...
2       cg12045430  GCCCGGGTCCCTGCGCCCCACAAGCCTTGGCTTCCCTGCTAGGGCC...
3       cg20826792  CACAAGCCTTGGCTTCCCTGCTAGGGCCGGGCAAGGCCGGGTGCAG...
4       cg00381604  GGCTTCCCTGCTAGGGCCGGGCAAGGCCGGGTGCAGGGCGCGGCTC...
...            ...                                                ...
485507  cg17939569  CCACCTTAGGGGCCTGTTGGGTAGCAAAGGGATTATGTTGTCCTTG...
485508  cg13365400  ACATCACATTACCTAGATGATGGGCCCATAGATATGTTATAGTTTT...
485509  cg21106100  CGGGGTGCCACCGGCCCGCCCGACCGGGTCCGTGCTGAGGAGAACA...
485510  cg08265308  CCCGCCCGACCGGGTCCGTGCTGAGGAGAACACTGCTCTGCCTTCC...
485511  cg14273923  GGCCGGGGCTGGTCAGAAAGATCCGAGCGTTGGGAGCCGGTGGAAG...

[485512 rows x 2 columns]

# Creating one hot matrix for the serrounding seq per CpG

Transferring the Probe To Seq DF to a oneHotEncoding representation

In [ ]:
# understanding the oneHotEncoding code
seqList = [0,1,2,1,3,4,0,1]
zeros = np.zeros((len(seqList),Conf.numBases),  dtype=int)
zeros[np.arange(len(seqList)),seqList] = int(1)
zeros

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0]])

In [ ]:
import csv

def seq_to_one_hot_mtrx(seq, probe):
    if 'N' in seq:
        print(f"N in seq {probe}. replaced with 5th value - 4")
    seq = seq.replace('A','0').replace('a','0').replace('C', '1').replace('c','1').replace('G', '2').replace('g','2').replace('T', '3').replace('t','3').replace('N','4')
    seqList = list(seq)
    seqList = [int(i) for i in seqList]
    one_hot = np.zeros((len(seq),Conf.numBases))
    one_hot[np.arange(len(seq)),seqList] = 1
    return one_hot.flatten()

def sequences_to_one_hot_mtrx(probe_to_serrounding_seq, path_one_hot):
  probe = probe_to_serrounding_seq["Probe"].iloc[0]
  seq = probe_to_serrounding_seq["Seq"].iloc[0]
  oneHotMtrx = seq_to_one_hot_mtrx(seq, str(probe))
  len_seq_one_hot = len(oneHotMtrx.flatten())
  lst = range(len_seq_one_hot)
  probe_to_seq_one_hot = {}
  for i in range(probe_to_serrounding_seq.shape[0]):
      probe = probe_to_serrounding_seq["Probe"].iloc[i]
      seq = probe_to_serrounding_seq["Seq"].iloc[i]
      oneHotMtrx = seq_to_one_hot_mtrx(seq, str(probe))
      probe_to_seq_one_hot[probe] = oneHotMtrx.flatten()
      if i%1000 ==0:
        print(i)
  with open(path_one_hot, "w") as outfile:
      writer = csv.writer(outfile)
      cpg_list = list(probe_to_seq_one_hot.keys())
      lst = range(len_seq_one_hot)
      columns= ['Probe']+[format(x, '02d') for x in lst]
      writer.writerow(columns)
      for i, cpg in enumerate(cpg_list):
          row = [cpg] + list(probe_to_seq_one_hot[cpg])
          writer.writerow(row)

  return probe_to_seq_one_hot

In [ ]:
probe_to_seq_one_hot = sequences_to_one_hot_mtrx(probe_to_serrounding_seq, "/content/drive/MyDrive/MSC/CH3_Project/res/probe_to_surrounding_seq_one_hot_formatted.csv")

# Data paths

In [ ]:
# Full files paths:
distances = "/content/drive/MyDrive/MSC/CH3_Project/res/distances.csv"
expression = "/content/drive/MyDrive/MSC/CH3_Project/res/expression.csv"
labels = "/content/drive/MyDrive/MSC/CH3_Project/res/labels.csv"
one_hot_sequences = "/content/drive/MyDrive/MSC/CH3_Project/res/probe_to_surrounding_seq_one_hot_formatted.csv"


# Sampled files paths:
distances_sampled = "/content/drive/MyDrive/MSC/CH3_Project/res/distances_cpg_sampled.csv"
expression_sampled =  "/content/drive/MyDrive/MSC/CH3_Project/res/expression.csv"
labels_sampled = "/content/drive/MyDrive/MSC/CH3_Project/res/labels_sampled.csv"
one_hot_sequences_sampled = "/content/drive/MyDrive/MSC/CH3_Project/res/probe_to_surrounding_seq_one_hot_formatted_sampled.csv"

In [ ]:
import pandas as pd

In [ ]:
# crearing sampled data
import pandas as pd
to_create_samples = False

if to_create_samples:
  labels_df_sampled = pd.read_csv("/content/drive/MyDrive/MSC/CH3_Project/res/labels_sampled.csv")
  labels_df_sampled
  cpgs = list(labels_df_sampled["Probe"])
  df_one_hot = pd.read_csv("/content/drive/MyDrive/MSC/CH3_Project/res/probe_to_surrounding_seq_one_hot_formatted.csv", index=False)
  df_one_hot_sampled = df_one_hot[df_one_hot['Probe'].isin(cpgs)]
  df_one_hot_sampled
  df_one_hot_sampled.to_csv("/content/drive/MyDrive/MSC/CH3_Project/res/probe_to_surrounding_seq_one_hot_formatted_sampled.csv", index=False)