In [ ]:
import pandas as pd

labels = pd.read_csv("../full/full_27_03/labels_methyl.csv")
dist = pd.read_csv("../full/full_27_03/distances_2k_full.csv")
exp = pd.read_csv("../full/full_27_03/expression.csv")
seq = pd.read_csv("../full/full_27_03/probe_to_surrounding_seq_one_hot_formatted.csv")

In [ ]:
labels = pd.read_csv("../full/full_27_03/labels_methyl.csv")
dist = pd.read_csv("../full/full_27_03/distances_2k_full.csv")
exp = pd.read_csv("../full/full_27_03/expression.csv")
seq = pd.read_csv("../full/full_27_03/probe_to_surrounding_seq_one_hot_formatted.csv")

In [ ]:
exp = pd.read_csv("../full/full_27_03/expression.csv")

In [ ]:
sampled_size = 100000
SAMPLED_PATH = './sam_100k/'

In [ ]:
sampled_labels = labels.sample(n=sampled_size+1, random_state=1)
sampled_labels.to_csv(SAMPLED_PATH +'sampled_labels.csv', index=False)
sampled_labels.head(5)

,Probe,TCGA.3C.AAAU.01,TCGA.3C.AALI.01,TCGA.3C.AALJ.01,TCGA.3C.AALK.01,TCGA.4H.AAAK.01,TCGA.5L.AAT0.01,TCGA.5L.AAT1.01,TCGA.5T.A9QA.01,TCGA.A1.A0SB.01,...,TCGA.NJ.A4YG.01,TCGA.NJ.A4YI.01,TCGA.NJ.A4YP.01,TCGA.NJ.A4YQ.01,TCGA.NJ.A55A.01,TCGA.NJ.A55O.01,TCGA.NJ.A55R.01,TCGA.NJ.A7XG.01,TCGA.O1.A52J.01,TCGA.S2.AA1A.01
43209,cg12040486,0.0520,0.0590,0.0603,0.4113,0.0425,0.0488,0.1216,0.3588,0.0426,...,0.2537,0.0932,0.4304,0.0950,0.2706,0.1165,0.1404,0.0810,0.0961,0.1344
179303,cg12422199,0.7198,0.6719,0.6432,0.7279,0.7885,0.6232,0.6925,0.7276,0.5664,...,0.5868,0.7517,0.7277,0.6659,0.6508,0.7189,0.6054,0.6559,0.6019,0.7379
24632,cg01417625,0.8335,0.8670,0.7933,0.8694,0.8749,0.7467,0.8449,0.8694,0.6394,...,0.7162,0.7757,0.7870,0.6904,0.5598,0.6948,0.6686,0.7183,0.2643,0.6762
169791,cg22110888,0.7104,0.3545,0.4479,0.4281,0.5229,0.5937,0.6001,0.3578,0.6796,...,0.8977,0.9295,0.9135,0.7147,0.8841,0.8802,0.8305,0.9150,0.9082,0.8878
103258,cg07370745,0.9364,0.9121,0.8836,0.9269,0.9368,0.8704,0.8663,0.9107,0.9176,...,0.8257,0.8677,0.8426,0.6321,0.6950,0.8467,0.7512,0.8490,0.7949,0.7253

In [ ]:
sampled_dist = dist.loc[dist['Probe'].isin(sampled_labels['Probe'])]
sampled_dist.to_c`sv(SAMPLED_PATH + 'sampled_dist.csv', index=False)
sampled_dist.head(5)

,Probe,WASH7P,OR4F5,OR4F29,LOC100132287,LOC100133331,FAM41C,SAMD11,NOC2L,KLHL17,...,OR2G6,OR2T34,OR2T11,OR2T35,OR2T27,OR14I1,SH3BP5L,ZNF672,ZNF692,PGBD2
0,cg00007221,-2.273520e-08,-2.276352e-08,-2.296302e-08,-2.298414e-08,-2.310896e-08,-2.318521e-08,-2.321636e-08,-2.322647e-08,-2.323510e-08,...,4.889435e-09,4.888188e-09,4.886937e-09,4.886648e-09,4.886370e-09,4.885619e-09,4.882505e-09,4.881662e-09,4.881590e-09,4.879993e-09
3,cg00026546,-2.999362e-08,-3.004294e-08,-3.039140e-08,-3.042840e-08,-3.064756e-08,-3.078181e-08,-3.083675e-08,-3.085459e-08,-3.086983e-08,...,4.647556e-09,4.646430e-09,4.645299e-09,4.645038e-09,4.644787e-09,4.644108e-09,4.641295e-09,4.640533e-09,4.640467e-09,4.639025e-09
5,cg00057791,-7.966337e-08,-8.001221e-08,-8.253247e-08,-8.280595e-08,-8.444930e-08,-8.547657e-08,-8.590149e-08,-8.604009e-08,-8.615870e-08,...,4.238106e-09,4.237169e-09,4.236229e-09,4.236012e-09,4.235803e-09,4.235239e-09,4.232899e-09,4.232265e-09,4.232210e-09,4.231011e-09
10,cg00074184,-8.583325e-09,-8.587359e-09,-8.615596e-09,-8.618567e-09,-8.636058e-09,-8.646685e-09,-8.651014e-09,-8.652418e-09,-8.653616e-09,...,7.575624e-09,7.572632e-09,7.569630e-09,7.568936e-09,7.568269e-09,7.566469e-09,7.559003e-09,7.556982e-09,7.556808e-09,7.552983e-09
18,cg00173787,-6.382252e-09,-6.384482e-09,-6.400077e-09,-6.401716e-09,-6.411362e-09,-6.417217e-09,-6.419601e-09,-6.420374e-09,-6.421034e-09,...,1.089054e-08,1.088436e-08,1.087816e-08,1.087673e-08,1.087535e-08,1.087163e-08,1.085623e-08,1.085206e-08,1.085170e-08,1.084381e-08

In [ ]:
sampled_seq = seq.loc[seq['Probe'].isin(sampled_labels['Probe'])]
sampled_seq.to_csv(SAMPLED_PATH + 'sampled_seq.csv', index=False)
sampled_seq.head(5)

,Probe,00,01,02,03,04,05,06,07,08,...,3990,3991,3992,3993,3994,3995,3996,3997,3998,3999
11,cg22802167,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
15,cg24159721,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
19,cg00645010,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
20,cg15394630,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
22,cg03344490,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [ ]:
# sampled_exp = exp.sample(n=sampled_size, random_state=1)
sampled_exp = exp
sampled_exp.to_csv(SAMPLED_PATH + 'sampled_exp.csv', index=False)
sampled_exp.head(5)

,Unnamed: 0,ARHGEF10L,HIF3A,RNF17,RNF10,RNF11,RNF13,GTF2IP1,REM1,MTVR2,...,TULP2,NPY5R,GNGT2,GNGT1,TULP3,PTRF,BCL6B,GSTK1,SELP,SELS
0,TCGA.3C.AAAU.01,10.4713,2.3606,0.0000,11.6317,11.2053,10.1911,12.3502,4.0452,0.7564,...,0.0000,2.1527,3.7074,0.0000,8.9560,11.4006,7.8250,12.1997,5.6018,9.7282
1,TCGA.3C.AALI.01,9.2228,0.6265,0.6265,11.8757,10.4259,10.1674,12.4482,4.1138,2.2650,...,1.0618,1.6668,4.9499,3.2780,9.3888,12.1666,8.1093,10.7031,5.5942,10.0766
2,TCGA.3C.AALJ.01,10.9468,0.9310,0.0000,12.2616,10.7842,9.5713,12.7540,4.9504,0.0000,...,0.0000,0.9310,4.2579,1.4922,9.3284,12.5534,8.7597,12.0469,5.6941,10.1682
3,TCGA.3C.AALK.01,9.9856,2.6732,0.0000,11.9567,11.0071,10.0354,12.6732,5.0382,0.0000,...,1.1643,1.4087,4.2634,0.0000,9.3354,13.0257,7.9614,11.3719,8.6253,10.2333
4,TCGA.4H.AAAK.01,10.2842,2.2720,0.0000,11.7566,10.8499,9.9325,12.3191,3.1835,0.8884,...,1.4341,0.8884,3.9904,0.0000,9.0038,13.1156,7.6902,10.8298,5.7256,10.0402

In [ ]:
sam_labels = pd.read_csv(SAMPLED_PATH +'sampled_labels.csv')
sam_dist = pd.read_csv(SAMPLED_PATH +'sampled_dist.csv')
sam_exp = pd.read_csv(SAMPLED_PATH +'sampled_exp.csv')
sam_seq = pd.read_csv(SAMPLED_PATH +'sampled_seq.csv')

In [ ]:
sam_labels.shape

(100001, 1351)

In [ ]:
sam_dist.shape

(529, 1823)

In [ ]:
sam_exp.shape

(1350, 20157)

In [ ]:
sam_seq.shape

(99983, 4001)

In [ ]:
sam_labels

,Probe,TCGA.3C.AAAU.01,TCGA.3C.AALI.01,TCGA.3C.AALJ.01,TCGA.3C.AALK.01,TCGA.4H.AAAK.01,TCGA.5L.AAT0.01,TCGA.5L.AAT1.01,TCGA.5T.A9QA.01,TCGA.A1.A0SB.01,...,TCGA.NJ.A4YG.01,TCGA.NJ.A4YI.01,TCGA.NJ.A4YP.01,TCGA.NJ.A4YQ.01,TCGA.NJ.A55A.01,TCGA.NJ.A55O.01,TCGA.NJ.A55R.01,TCGA.NJ.A7XG.01,TCGA.O1.A52J.01,TCGA.S2.AA1A.01
0,cg12040486,0.0520,0.0590,0.0603,0.4113,0.0425,0.0488,0.1216,0.3588,0.0426,...,0.2537,0.0932,0.4304,0.0950,0.2706,0.1165,0.1404,0.0810,0.0961,0.1344
1,cg12422199,0.7198,0.6719,0.6432,0.7279,0.7885,0.6232,0.6925,0.7276,0.5664,...,0.5868,0.7517,0.7277,0.6659,0.6508,0.7189,0.6054,0.6559,0.6019,0.7379
2,cg01417625,0.8335,0.8670,0.7933,0.8694,0.8749,0.7467,0.8449,0.8694,0.6394,...,0.7162,0.7757,0.7870,0.6904,0.5598,0.6948,0.6686,0.7183,0.2643,0.6762
3,cg22110888,0.7104,0.3545,0.4479,0.4281,0.5229,0.5937,0.6001,0.3578,0.6796,...,0.8977,0.9295,0.9135,0.7147,0.8841,0.8802,0.8305,0.9150,0.9082,0.8878
4,cg07370745,0.9364,0.9121,0.8836,0.9269,0.9368,0.8704,0.8663,0.9107,0.9176,...,0.8257,0.8677,0.8426,0.6321,0.6950,0.8467,0.7512,0.8490,0.7949,0.7253
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99996,cg12936121,0.7129,0.0753,0.4621,0.4060,0.6223,0.7397,0.4925,0.9051,0.8889,...,0.4742,0.5979,0.5925,0.4863,0.5225,0.4390,0.3807,0.5610,0.4710,0.4014
99997,cg22803642,0.1528,0.2514,0.2903,0.2370,0.2502,0.2643,0.2608,0.3876,0.0898,...,0.6407,0.6420,0.4902,0.4341,0.5413,0.4959,0.5304,0.7293,0.4515,0.4187
99998,cg03904534,0.9464,0.9528,0.9488,0.8881,0.9625,0.9555,0.9287,0.9464,0.9561,...,0.8709,0.8868,0.9380,0.9456,0.9110,0.9282,0.9186,0.9628,0.9646,0.9814
99999,cg05613718,0.9500,0.8844,0.9399,0.9356,0.9447,0.9144,0.8453,0.9328,0.9548,...,0.8565,0.7524,0.7973,0.7652,0.8100,0.8094,0.8248,0.8528,0.7507,0.8709
100000,cg27180671,0.6889,0.5383,0.7125,0.7474,0.7109,0.5484,0.6529,0.8621,0.1511,...,0.3593,0.2636,0.5825,0.5318,0.4989,0.5027,0.3097,0.3411,0.6066,0.4352

In [ ]:
sam_dist.head(5)

,Probe,WASH7P,OR4F5,OR4F29,LOC100132287,LOC100133331,FAM41C,SAMD11,NOC2L,KLHL17,...,OR2G6,OR2T34,OR2T11,OR2T35,OR2T27,OR14I1,SH3BP5L,ZNF672,ZNF692,PGBD2
0,cg00007221,-2.273520e-08,-2.276352e-08,-2.296302e-08,-2.298414e-08,-2.310896e-08,-2.318521e-08,-2.321636e-08,-2.322647e-08,-2.323510e-08,...,4.889435e-09,4.888188e-09,4.886937e-09,4.886648e-09,4.886370e-09,4.885619e-09,4.882505e-09,4.881662e-09,4.881590e-09,4.879993e-09
1,cg00026546,-2.999362e-08,-3.004294e-08,-3.039140e-08,-3.042840e-08,-3.064756e-08,-3.078181e-08,-3.083675e-08,-3.085459e-08,-3.086983e-08,...,4.647556e-09,4.646430e-09,4.645299e-09,4.645038e-09,4.644787e-09,4.644108e-09,4.641295e-09,4.640533e-09,4.640467e-09,4.639025e-09
2,cg00057791,-7.966337e-08,-8.001221e-08,-8.253247e-08,-8.280595e-08,-8.444930e-08,-8.547657e-08,-8.590149e-08,-8.604009e-08,-8.615870e-08,...,4.238106e-09,4.237169e-09,4.236229e-09,4.236012e-09,4.235803e-09,4.235239e-09,4.232899e-09,4.232265e-09,4.232210e-09,4.231011e-09
3,cg00074184,-8.583325e-09,-8.587359e-09,-8.615596e-09,-8.618567e-09,-8.636058e-09,-8.646685e-09,-8.651014e-09,-8.652418e-09,-8.653616e-09,...,7.575624e-09,7.572632e-09,7.569630e-09,7.568936e-09,7.568269e-09,7.566469e-09,7.559003e-09,7.556982e-09,7.556808e-09,7.552983e-09
4,cg00173787,-6.382252e-09,-6.384482e-09,-6.400077e-09,-6.401716e-09,-6.411362e-09,-6.417217e-09,-6.419601e-09,-6.420374e-09,-6.421034e-09,...,1.089054e-08,1.088436e-08,1.087816e-08,1.087673e-08,1.087535e-08,1.087163e-08,1.085623e-08,1.085206e-08,1.085170e-08,1.084381e-08

In [ ]:
sam_exp.head(5)

,Unnamed: 0,ARHGEF10L,HIF3A,RNF17,RNF10,RNF11,RNF13,GTF2IP1,REM1,MTVR2,...,TULP2,NPY5R,GNGT2,GNGT1,TULP3,PTRF,BCL6B,GSTK1,SELP,SELS
0,TCGA.3C.AAAU.01,10.4713,2.3606,0.0000,11.6317,11.2053,10.1911,12.3502,4.0452,0.7564,...,0.0000,2.1527,3.7074,0.0000,8.9560,11.4006,7.8250,12.1997,5.6018,9.7282
1,TCGA.3C.AALI.01,9.2228,0.6265,0.6265,11.8757,10.4259,10.1674,12.4482,4.1138,2.2650,...,1.0618,1.6668,4.9499,3.2780,9.3888,12.1666,8.1093,10.7031,5.5942,10.0766
2,TCGA.3C.AALJ.01,10.9468,0.9310,0.0000,12.2616,10.7842,9.5713,12.7540,4.9504,0.0000,...,0.0000,0.9310,4.2579,1.4922,9.3284,12.5534,8.7597,12.0469,5.6941,10.1682
3,TCGA.3C.AALK.01,9.9856,2.6732,0.0000,11.9567,11.0071,10.0354,12.6732,5.0382,0.0000,...,1.1643,1.4087,4.2634,0.0000,9.3354,13.0257,7.9614,11.3719,8.6253,10.2333
4,TCGA.4H.AAAK.01,10.2842,2.2720,0.0000,11.7566,10.8499,9.9325,12.3191,3.1835,0.8884,...,1.4341,0.8884,3.9904,0.0000,9.0038,13.1156,7.6902,10.8298,5.7256,10.0402

In [ ]:
sam_exp

In [ ]:
sam_seq.head(5)

,Probe,00,01,02,03,04,05,06,07,08,...,3990,3991,3992,3993,3994,3995,3996,3997,3998,3999
0,cg22802167,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,cg24159721,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,cg00645010,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
3,cg15394630,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,cg03344490,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [ ]:
sampled_exp

In [ ]:
MINI_PATH = './mini/'
sam_labels = pd.read_csv(MINI_PATH +'ch3_sample_mini.csv')
sam_dist = pd.read_csv(MINI_PATH +'d_sample_mini.csv')
sam_exp = pd.read_csv(MINI_PATH +'e_sample_mini.csv')
sam_seq = pd.read_csv(MINI_PATH +'probeToOneHotAll_sample_mini.csv')

In [ ]:
sam_labels.head(5)

,Probe,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,...,s_16,s_17,s_18,s_19,s_20,s_21,s_22,s_23,s_24,s_25
0,cg_1,0.9210,0.9410,0.9521,0.9549,0.9160,0.9330,0.9390,0.9065,0.8687,...,0.8989,0.9305,0.9198,0.9389,0.9436,0.9480,0.9266,0.9555,0.9497,0.9389
1,cg_2,0.0604,0.0467,0.0523,0.0435,0.0550,0.0546,0.0488,0.0630,0.0427,...,0.0496,0.0629,0.0902,0.0777,0.0513,0.0385,0.0577,0.0560,0.0450,0.0452
2,cg_3,0.7576,0.7279,0.7216,0.7746,0.5195,0.6078,0.6635,0.7010,0.8076,...,0.6792,0.7933,0.8133,0.8027,0.7338,0.7896,0.7235,0.7358,0.8099,0.7366
3,cg_4,0.8899,0.9082,0.8777,0.8703,0.8341,0.8572,0.8799,0.8326,0.7437,...,0.7266,0.7329,0.6559,0.7073,0.8943,0.8783,0.9132,0.8924,0.8576,0.9082
4,cg_5,0.0385,0.0337,0.0422,0.0458,0.0520,0.0506,0.0408,0.0362,0.0331,...,0.0833,0.0571,0.0593,0.0529,0.0394,0.0465,0.0308,0.0386,0.0484,0.0464

In [ ]:
sam_dist.shape

(25, 17997)

In [ ]:
sam_exp.shape

(25, 17997)

In [ ]:
sam_seq.shape

(25, 4001)